"""Phase 1: Field catalogue per raw endpoint, generated by DeepSeek.

For each unique source/endpoint family in ``data/raw/`` we send DeepSeek the
representative snapshot body plus structured instructions. DeepSeek returns
a machine-readable catalogue (JSON, validated against ``CATALOG_SCHEMA``)
describing every leaf field's semantics, type, sample values, nullability,
nested-table risk and collision risk with sibling endpoints.

These catalogues feed Phase 2 (canonical schema design) and Phase 5
(gap-scan: surface fields no canonical record yet exposes).
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..deepseek import DeepSeekClient
from ..storage import write_json
from . import PIPELINE_NAME, __version__
from .endpoint_picker import EndpointSample, iter_endpoint_samples
from .metadata import (
    SourceRef,
    build_envelope,
    schema_url,
    utc_now_iso,
)


CATALOG_SCHEMA_NAME = "raw_catalog/endpoint.schema"
CATALOG_SCHEMA_VERSION = "1.0.0"

# Hard cap on snapshot body sent to DeepSeek. Most endpoints are well under
# this; large ones (e.g., BSE performance dumps with thousands of rows) get
# truncated with a notice — we only need the *shape*, not every row.
MAX_BODY_CHARS = 80_000

SYSTEM_PROMPT = """You are a senior data engineer cataloguing a stock-exchange API response so a downstream team can build a canonical schema for Indian IPO data.

Your job: emit a JSON catalogue describing every leaf field in the supplied snapshot body, with semantic interpretation AND contamination risk analysis. The downstream team will use this catalogue to design schemas, write parsers, and identify gaps. Accuracy beats coverage — flag uncertainty explicitly rather than guess.

Rules:
1. Walk the entire JSON. Enumerate every distinct leaf path (JSONPath-style). If the body is a list-of-objects, treat the array element shape as canonical and note variations.
2. For each leaf, infer: semantic meaning in plain English, data type (string|integer|number|boolean|date|datetime|currency|percent|null), units if applicable (INR, %, x, shares, basis_points, paise), example values seen, whether nulls appear and what they mean, whether the value is itself a nested table or HTML blob that hides more structure, whether this field could collide with a same-named field from a sibling endpoint (different semantics).
3. Identify nested endpoints referenced by ID (e.g., "this row has a Scrip_cd that should be joined to ..."). List them under nested_endpoints_referenced.
4. For EACH field, identify contamination risks the v2 normalizer must guard against. Possible risk categories (use these category prefixes):
   - E.ID  identifier collision / stability  (e.g., source_record_id reused, name variants, symbol reuse, PAN typos)
   - E.CUR currency / units / magnitude       (lakhs vs crores vs rupees, mixed-scale rows, circuit-locked zeros)
   - E.DAT date / time / timezone             (dd-MMM-yyyy parsing, naive IST timestamps, date revisions, weekend adjusts)
   - E.NUM number parsing                     (Indian comma format, numbers-as-strings, float precision)
   - E.SUB subscription / bid book            (anchor vs total QIB, gross vs net, NSE/BSE disagreement)
   - E.SRC source merging / precedence        (multi-source disagreement, enrichment masking primary)
   - E.STA status / state machine             (withdrawn, OFS conflation, suspended)
   - E.HTM HTML / encoding                    (HTML in description, non-ASCII names, BOM/CRLF)
   - E.SNP snapshot lifecycle                 (empty body sentinels, stale data, cache poisoning)
   - E.PAG pagination / dropdown              (ASP.NET form state, dropdown-dependent data)
   - E.UPS upstream schema drift              (renames, additions, type changes)
   - E.LEG regulatory                         (silent period, PII)
5. If you see HTML, dropdown payloads, or anything suggesting a separate request is needed to expand the data (pagination tokens, ViewState, dropdown date pickers, AJAX form posts), flag under warnings.
6. Estimate refresh cadence (minutes between fetches) and staleness tolerance (hours after which the data should be considered degraded), based on what kind of data this is (subscription = minutes, performance history = days).
7. Flag personally identifiable information (PAN, DIN, contact info, addresses).
8. Output STRICT JSON matching the schema in the user message. No prose, no markdown fences, no commentary outside the JSON."""

USER_TEMPLATE = """ENDPOINT METADATA
source: {source}
endpoint_family: {endpoint_group}
representative_concrete_endpoint: {endpoint_concrete}
url: {url}
snapshot_at: {snapshot_at}
body_size_bytes: {body_bytes}
body_truncated: {truncated}

REQUIRED OUTPUT SCHEMA (JSON, no markdown):
{{
  "source": "{source}",
  "endpoint": "{endpoint_group}",
  "summary": "<one-paragraph plain-English description of what this endpoint provides>",
  "row_shape": "list_of_objects | dict | scalar | html_blob | mixed",
  "row_count_observed": <integer or null>,
  "data_kind": "live_subscription | live_quote | issue_metadata | document_index | performance_history | dropdown_index | calendar | other",
  "refresh_cadence_minutes_suggested": <integer or null, e.g., 30 for live subscription, 1440 for performance history>,
  "staleness_tolerance_hours_suggested": <integer or null>,
  "fields": [
    {{
      "path": "<JSONPath, e.g., $[*].symbol or $.Table[*].IPO_NO>",
      "name": "<short field name>",
      "type": "string | integer | number | boolean | date | datetime | currency | percent | url | identifier | enum | object | array | null",
      "semantic": "<plain English meaning, 1 sentence>",
      "units": "<INR | paise | % | bps | x | shares | lot | null>",
      "examples": ["<sample value>", "..."],
      "nullable": <true|false>,
      "null_meaning": "<what null indicates, or null if N/A>",
      "nested_table": <true|false>,
      "dropdown_dependent": <true|false>,
      "html_content": <true|false>,
      "is_identifier": <true|false>,
      "is_pii": <true|false>,
      "collision_risk_with": ["<source.endpoint.field if you see a sibling endpoint with same name but different meaning, else empty>"],
      "contamination_risks": [
        {{"category": "E.ID | E.CUR | E.DAT | E.NUM | E.SUB | E.SRC | E.STA | E.HTM | E.SNP | E.PAG | E.UPS | E.LEG",
          "description": "<concrete risk this field exposes, e.g., 'numbers reported as strings'>",
          "suggested_mitigation": "<concrete normalizer behavior, e.g., 'coerce_int after stripping commas'>"}}
      ],
      "canonical_field_hint": "<suggested canonical field name in a unified schema, e.g., 'pricing.price_band.upper_paise'>",
      "notes": "<gotchas, format quirks, e.g., 'dd-MMM-yyyy' or 'Rs. 1.5 cr as text'>"
    }}
  ],
  "nested_endpoints_referenced": [
    {{"description": "...", "key_field": "...", "follow_up_endpoint_pattern": "..."}}
  ],
  "pii_fields": ["<paths to PII fields, e.g., $[*].pan_no>"],
  "warnings": ["<freeform alerts: pagination, dropdowns, missing data, HTML blobs, etc.>"]
}}

SNAPSHOT BODY (JSON):
{body}
"""


@dataclass(frozen=True)
class CatalogResult:
    sample: EndpointSample
    output_path: Path
    cached: bool
    tokens_in: int
    tokens_out: int
    cost_usd: float


def catalog_endpoint(
    sample: EndpointSample,
    client: DeepSeekClient,
    out_root: Path,
    model: str = "deepseek-chat",
) -> CatalogResult:
    """Catalog one endpoint and write the result to disk.

    The output JSON is wrapped in the standard documentation envelope so a
    downstream consumer reading a single file in isolation knows what it is.
    """
    body_text = _read_body_text(sample.snapshot_path)
    truncated = len(body_text) > MAX_BODY_CHARS
    if truncated:
        body_text = body_text[:MAX_BODY_CHARS] + '\n... [TRUNCATED]'

    user_prompt = USER_TEMPLATE.format(
        source=sample.source,
        endpoint_group=sample.endpoint_group,
        endpoint_concrete=sample.endpoint_concrete,
        url=sample.url,
        snapshot_at=sample.snapshot_at,
        body_bytes=sample.body_bytes,
        truncated=str(truncated).lower(),
        body=body_text,
    )

    response = client.chat(
        user=user_prompt,
        system=SYSTEM_PROMPT,
        model=model,
        temperature=0.0,
        response_format="json_object",
        purpose=f"catalog:{sample.source}:{sample.endpoint_group}",
        extra_telemetry={
            "endpoint_concrete": sample.endpoint_concrete,
            "body_bytes": sample.body_bytes,
            "truncated": truncated,
        },
    )

    catalog_body = response.json_content
    if not isinstance(catalog_body, dict):
        raise RuntimeError(
            f"Catalog response for {sample.source}/{sample.endpoint_group} "
            f"was not a JSON object: {response.content[:200]}"
        )

    envelope = build_envelope(
        schema_name=CATALOG_SCHEMA_NAME,
        schema_version=CATALOG_SCHEMA_VERSION,
        sources=[
            SourceRef(
                source=sample.source,
                endpoint=sample.endpoint_concrete,
                snapshot_at=sample.snapshot_at,
                url=sample.url,
                confidence="primary",
            )
        ],
        notes=(
            "Auto-generated by DeepSeek from a representative raw snapshot. "
            "This document describes the shape of upstream data, not the "
            "canonical v2 schema."
        ),
        extra={
            "catalog_metadata": {
                "model": response.model,
                "tokens_in": response.prompt_tokens,
                "tokens_out": response.completion_tokens,
                "estimated_cost_usd": response.estimated_cost_usd,
                "cached": response.cached,
                "endpoint_concrete": sample.endpoint_concrete,
                "body_truncated": truncated,
                "pipeline": f"{PIPELINE_NAME}/{__version__}",
            }
        },
    )

    document = {**envelope, **catalog_body}

    output_path = out_root / sample.source / f"{sample.endpoint_group}.json"
    document["schema_url_self"] = f"docs/schema/raw_catalog/{sample.source}/{sample.endpoint_group}.json"
    write_json(output_path, document)

    return CatalogResult(
        sample=sample,
        output_path=output_path,
        cached=response.cached,
        tokens_in=response.prompt_tokens,
        tokens_out=response.completion_tokens,
        cost_usd=response.estimated_cost_usd,
    )


def catalog_all(
    raw_root: Path,
    out_root: Path,
    client: DeepSeekClient | None = None,
    model: str = "deepseek-chat",
    only: list[str] | None = None,
    limit: int | None = None,
) -> list[CatalogResult]:
    """Catalog every (source, endpoint_group) in raw_root.

    ``only`` filters to endpoint_group names exactly (useful for piloting on
    one endpoint before scaling). ``limit`` caps the number of endpoints.
    """
    client = client or DeepSeekClient()
    samples = list(iter_endpoint_samples(raw_root))
    if only:
        wanted = set(only)
        samples = [s for s in samples if s.endpoint_group in wanted or s.endpoint_concrete in wanted]
    if limit is not None:
        samples = samples[:limit]

    results: list[CatalogResult] = []
    for sample in samples:
        result = catalog_endpoint(sample, client=client, out_root=out_root, model=model)
        results.append(result)
    _write_index(out_root, results)
    return results


def _read_body_text(path: Path) -> str:
    payload = json.loads(path.read_text(encoding="utf-8"))
    body = payload.get("body")
    return json.dumps(body, ensure_ascii=False, indent=2)


def _write_index(out_root: Path, results: list[CatalogResult]) -> None:
    """Write a top-level index over the catalogue tree."""
    if not results:
        return
    by_source: dict[str, list[dict[str, Any]]] = {}
    for r in results:
        by_source.setdefault(r.sample.source, []).append(
            {
                "endpoint_group": r.sample.endpoint_group,
                "endpoint_concrete": r.sample.endpoint_concrete,
                "url": r.sample.url,
                "snapshot_at": r.sample.snapshot_at,
                "body_bytes": r.sample.body_bytes,
                "catalog_path": str(r.output_path.relative_to(out_root.parent.parent)) if r.output_path.is_absolute() else str(r.output_path),
                "tokens_in": r.tokens_in,
                "tokens_out": r.tokens_out,
                "estimated_cost_usd": r.cost_usd,
                "cached": r.cached,
            }
        )

    index_envelope = build_envelope(
        schema_name="raw_catalog/index.schema",
        schema_version=CATALOG_SCHEMA_VERSION,
        notes=(
            "Index of all raw endpoint catalogues generated by Phase 1. "
            "Each entry points to a per-endpoint JSON describing the upstream "
            "shape; the canonical v2 schema is derived from this set in Phase 2."
        ),
    )
    document = {
        **index_envelope,
        "schema_url_self": "docs/schema/raw_catalog/index.json",
        "generated_at": utc_now_iso(),
        "by_source": by_source,
        "total_endpoints": sum(len(v) for v in by_source.values()),
        "total_cost_usd": sum(r.cost_usd for r in results),
        "total_tokens_in": sum(r.tokens_in for r in results),
        "total_tokens_out": sum(r.tokens_out for r in results),
        "schema_url": schema_url(CATALOG_SCHEMA_NAME),
    }
    write_json(out_root / "index.json", document)
